/**
 * RunTrim Bridge Mode — file writers and prompt builder.
 *
 * Bridge Mode places RunTrim between any AI coding agent and the codebase.
 * These helpers write the protocol files that guide the external agent.
 */

import fs from "fs";
import path from "path";
import { getConfigDir } from "./runtrim-config";
import type { ContractResult } from "./run-contract";

// ── Marker used when appending to CLAUDE.md / AGENTS.md ──────────────────────
const BRIDGE_START = "<!-- RUNTRIM_BRIDGE_START -->";
const BRIDGE_END   = "<!-- RUNTRIM_BRIDGE_END -->";

const BRIDGE_BLOCK = `
${BRIDGE_START}
Before editing code, read RUNTRIM.md and .runtrim/contracts/latest.md.
Stay inside the active scoped contract.
Do not touch forbidden files or unrelated systems.
If scope expands, stop and ask for a new RunTrim run.
After editing, run: runtrim finish
${BRIDGE_END}
`;

// ── Derived context ───────────────────────────────────────────────────────────

export interface BridgeContext {
  task: string;
  goal: string;
  riskLevel: string;
  tokenBudget: number;
  allowedScope: string[];
  forbiddenScope: string[];
  stopConditions: string[];
  verificationSteps: string[];
  memoryContext: string;
  projectName: string;
}

const TOKEN_BUDGET_MAP: Record<string, number> = {
  low:      10_000,
  medium:   25_000,
  high:     40_000,
  critical: 50_000,
};

export function deriveBridgeContext(
  task: string,
  contract: ContractResult,
  recentRuns: { task: string; status: string; createdAt: string }[],
  projectName: string
): BridgeContext {
  const c = contract.contract;
  const riskLevel = contract.wasteRiskAfter ?? "medium";
  const tokenBudget = TOKEN_BUDGET_MAP[riskLevel] ?? 25_000;

  const stopConditions = [
    ...(c.stopRules ?? []),
    ...(c.whenToAsk ?? []).map((s) => `Stop if: ${s}`),
  ];

  const verificationSteps = c.successCriteria ?? [];

  const lines = recentRuns.slice(0, 3).map((r) => {
    const day = new Date(r.createdAt).toLocaleDateString("en-US", {
      month: "short", day: "numeric",
    });
    return `- ${r.task} (${r.status}, ${day})`;
  });

  const memoryContext =
    lines.length > 0
      ? `Recent runs:\n${lines.join("\n")}`
      : "No prior runs. This is the first run for this project.";

  return {
    task,
    goal: c.cleanedObjective || task,
    riskLevel,
    tokenBudget,
    allowedScope: c.relevantScope ?? [],
    forbiddenScope: c.forbiddenScope ?? [],
    stopConditions,
    verificationSteps,
    memoryContext,
    projectName,
  };
}

// ── File writers ──────────────────────────────────────────────────────────────

export function writeContractFile(ctx: BridgeContext, cwd = process.cwd()): void {
  const dir = path.join(getConfigDir(cwd), "contracts");
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });

  const scopeLines = ctx.allowedScope.length > 0
    ? ctx.allowedScope.map((s) => `- ${s}`)
    : ["- Scope not explicitly defined. Stay close to the task description."];

  const forbidLines = ctx.forbiddenScope.length > 0
    ? ctx.forbiddenScope.map((s) => `- ${s}`)
    : ["- .env* files", "- auth logic", "- database schema / migrations", "- billing and payment logic"];

  const stopLines = ctx.stopConditions.length > 0
    ? ctx.stopConditions.map((s) => `- ${s}`)
    : [
        "- Stop if scope must expand beyond the task.",
        "- Stop if a forbidden area needs to be touched.",
        "- Stop if more than 5 files require changes.",
      ];

  const verifyLines = ctx.verificationSteps.length > 0
    ? ctx.verificationSteps.map((s) => `- ${s}`)
    : ["- Verify the behavior described in the task.", "- Check no unrelated files changed."];

  const lines = [
    "# RunTrim Active Contract",
    "",
    `Task: ${ctx.task}`,
    `Goal: ${ctx.goal}`,
    `Risk: ${ctx.riskLevel}`,
    `Token budget: ~${ctx.tokenBudget.toLocaleString()}`,
    `Created: ${new Date().toISOString()}`,
    "",
    "## Allowed scope",
    ...scopeLines,
    "",
    "## Forbidden scope",
    ...forbidLines,
    "",
    "## Stop conditions",
    ...stopLines,
    "",
    "## Verification steps",
    ...verifyLines,
    "",
    "---",
    "Generated by RunTrim Bridge. Do not edit manually.",
  ];

  fs.writeFileSync(path.join(dir, "latest.md"), lines.join("\n"), "utf-8");
}

export function writeMemoryFile(ctx: BridgeContext, cwd = process.cwd()): void {
  const dir = path.join(getConfigDir(cwd), "memory");
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });

  const noTouchLines = ctx.forbiddenScope.length > 0
    ? ctx.forbiddenScope.map((s) => `- ${s}`)
    : ["- .env files", "- auth logic", "- database schema", "- billing and payment logic"];

  const scopeLines = ctx.allowedScope.length > 0
    ? ctx.allowedScope.map((s) => `- ${s}`)
    : ["- Defined in .runtrim/contracts/latest.md"];

  const lines = [
    "# RunTrim Memory Pack",
    "",
    `Project: ${ctx.projectName}`,
    `Current task: ${ctx.task}`,
    `Updated: ${new Date().toISOString()}`,
    "",
    "## Context",
    ctx.memoryContext,
    "",
    "## Do not touch",
    ...noTouchLines,
    "",
    "## Active task scope",
    ...scopeLines,
    "",
    "---",
    "Generated by RunTrim Bridge. Do not edit manually.",
  ];

  fs.writeFileSync(path.join(dir, "current.md"), lines.join("\n"), "utf-8");
}

export function writeBridgeInstructions(cwd = process.cwd()): void {
  const dir = path.join(getConfigDir(cwd), "bridge");
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });

  const lines = [
    "# RunTrim Agent Instructions",
    "",
    "You are operating inside a RunTrim-guarded session.",
    "",
    "## Before editing",
    "",
    "Read these files first:",
    "- RUNTRIM.md",
    "- .runtrim/contracts/latest.md",
    "- .runtrim/memory/current.md",
    "",
    "## During editing",
    "",
    "- Stay within the allowed scope defined in the contract.",
    "- If a change requires touching a forbidden area, STOP and tell the user.",
    "- Make minimal, targeted changes only.",
    "- Do not refactor, rename, or reorganize outside the task scope.",
    "- Do not add console.log statements or debug artifacts.",
    "- Do not install new dependencies without explicit approval.",
    "",
    "## After editing",
    "",
    "- Tell the user which files you changed and why.",
    "- The user will run: runtrim finish",
    "- Do not run runtrim commands yourself unless explicitly asked.",
    "",
    "---",
    "Generated by RunTrim Bridge. Do not edit manually.",
  ];

  fs.writeFileSync(path.join(dir, "agent-instructions.md"), lines.join("\n"), "utf-8");
}

export function writeRootProtocolFile(ctx: BridgeContext, cwd = process.cwd()): void {
  const lines = [
    "# RunTrim Protocol",
    "",
    "This project is guarded by RunTrim Bridge Mode.",
    "",
    "## Active session",
    "",
    `Task: ${ctx.task}`,
    `Risk: ${ctx.riskLevel}`,
    `Token budget: ~${ctx.tokenBudget.toLocaleString()}`,
    "",
    "## Before editing",
    "",
    "Read the active contract before making any changes:",
    "",
    "```",
    ".runtrim/contracts/latest.md",
    "```",
    "",
    "## Rules",
    "",
    "- Stay inside the active scoped contract.",
    "- Do not touch forbidden files or unrelated systems.",
    "- If scope must expand, stop and ask the user to start a new RunTrim session.",
    "- Keep changes minimal and targeted.",
    "- Do not refactor, reorganize, or rename outside the direct task.",
    "",
    "## After editing",
    "",
    "The user will run: runtrim finish",
    "",
    "Do not attempt to run runtrim commands yourself.",
    "",
    "---",
    `Generated by RunTrim Bridge. Updated: ${new Date().toISOString()}`,
  ];

  fs.writeFileSync(path.join(cwd, "RUNTRIM.md"), lines.join("\n"), "utf-8");
}

/** Appends bridge block to an existing file if not already present. Returns true if appended. */
export function appendBridgeBlock(filePath: string): boolean {
  if (!fs.existsSync(filePath)) return false;
  const content = fs.readFileSync(filePath, "utf-8");
  if (content.includes(BRIDGE_START)) return false;
  fs.writeFileSync(filePath, content.trimEnd() + "\n" + BRIDGE_BLOCK, "utf-8");
  return true;
}

export interface WriteBridgeFilesResult {
  /** Human-readable display labels. */
  written: string[];
  /**
   * Actual relative file paths that RunTrim wrote or appended to this session.
   * Used by `runtrim finish` to exclude these from agent drift evaluation.
   */
  managedPaths: string[];
}

export function writeBridgeFiles(
  ctx: BridgeContext,
  cwd: string
): WriteBridgeFilesResult {
  const written: string[] = [];
  const managedPaths: string[] = [];

  const track = (relativePath: string, label?: string) => {
    managedPaths.push(relativePath);
    written.push(label ?? relativePath);
  };

  writeRootProtocolFile(ctx, cwd);
  track("RUNTRIM.md");

  writeContractFile(ctx, cwd);
  track(".runtrim/contracts/latest.md");

  writeMemoryFile(ctx, cwd);
  track(".runtrim/memory/current.md");

  writeBridgeInstructions(cwd);
  track(".runtrim/bridge/agent-instructions.md");

  // Append block to CLAUDE.md and AGENTS.md only if they already exist
  if (appendBridgeBlock(path.join(cwd, "CLAUDE.md")))  track("CLAUDE.md", "CLAUDE.md (bridge block appended)");
  if (appendBridgeBlock(path.join(cwd, "AGENTS.md")))  track("AGENTS.md", "AGENTS.md (bridge block appended)");

  return { written, managedPaths };
}

// ── Guarded bridge prompt ─────────────────────────────────────────────────────

/**
 * Builds the full guarded prompt for an external agent.
 * Wraps the existing contractText with RunTrim Bridge instructions.
 */
export function buildBridgePrompt(contractText: string, ctx: BridgeContext): string {
  const allowedList = ctx.allowedScope.length > 0
    ? ctx.allowedScope.map((s) => `  - ${s}`).join("\n")
    : "  - Defined in .runtrim/contracts/latest.md";

  const forbidList = ctx.forbiddenScope.length > 0
    ? ctx.forbiddenScope.map((s) => `  - ${s}`).join("\n")
    : "  - .env files, auth, database schema, billing, payments";

  const stopList = ctx.stopConditions.length > 0
    ? ctx.stopConditions.slice(0, 4).map((s) => `  - ${s}`).join("\n")
    : "  - Stop if more than 5 files need changes.\n  - Stop if a forbidden area must be touched.";

  const header = [
    "RUNTRIM BRIDGE SESSION",
    `Task: ${ctx.task}`,
    `Risk: ${ctx.riskLevel}  |  Token budget: ~${ctx.tokenBudget.toLocaleString()}`,
    "",
    "ALLOWED SCOPE",
    allowedList,
    "",
    "FORBIDDEN SCOPE",
    forbidList,
    "",
    "STOP CONDITIONS",
    stopList,
    "",
  ].join("\n");

  const footer = [
    "",
    "RULES",
    "  - Read RUNTRIM.md and .runtrim/contracts/latest.md before touching any file.",
    "  - Inspect first. List relevant files before opening them.",
    "  - Make the minimal change required. No unrelated refactors.",
    "  - If scope must expand, stop immediately and tell the user.",
    "  - After editing, tell the user which files changed. They will run: runtrim finish",
    "",
  ].join("\n");

  return header + contractText + footer;
}
